# -*- coding: utf-8 -*-
"""warpping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpbCQMc8kr0DBFdkjdk5pslh_4NSvQpT
"""

import cv2, numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread("duck.jpg")

src = np.float32([[420,170],[650,150],[680,420],[400,440]])
dst = np.float32([[0,0],[300,0],[300,420],[0,420]])

H = cv2.getPerspectiveTransform(src, dst)
warp = cv2.warpPerspective(img, H, (300,420))

cv2_imshow(img)
cv2_imshow(warp)